from django.urls import path
from . import views
urlpatterns = [
    path('register/', views.register_player, name='register_player'),
    path('player/login/', views.login_player, name='login_player'),
    path('player/logout/', views.logout_player, name='logout_player'),
    path('', views.home),
    path('player/details/', views.player_details, name="player_details"),
    path('player/profile/', views.player_profile, name='player_profile'),
    path('player/view_team/<uuid:team_id>/', views.view_team_members, name='view_team_members'),
    path('player/edit_profile/', views.edit_profile, name='edit_profile'),
    path('player/dashboard/', views.player_dashboard, name='player_dashboard'),
    path('player/sports_registration/', views.register_for_sports, name='sports_registration'),
    path('player/make_base_payment/', views.make_base_payment, name="make_base_payment"),
    path('player/make_sports_payment/<uuid:tp_id>/', views.make_sports_payment, name="make_sport_payment"),
    path('player/print_receipt/<uuid:team_player_id>/', views.print_receipt, name="print_receipt"),
    path('admin/login/', views.admin_login, name='admin_login'),
    path('admin/logout/', views.admin_logout, name='admin_logout'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/pcr_approved_players/', views.pcr_approved_players, name='pcr_approved_players'),
    path('admin/pcr_approved_coaches/', views.pcr_approved_coaches, name='pcr_approved_coaches'),
    path('admin/firewallz_approved_players/', views.firewallz_approved_players, name='firewallz_approved_players'),
    path('admin/firewallz_approved_coaches/', views.firewallz_approved_coaches, name='firewallz_approved_coaches'),
    path('admin/colleges/', views.college_list, name='college_list'),
    path('admin/players_per_college/<uuid:college_id>/', views.players_per_college, name='players_per_college'),
    path('admin/teams/', views.team_list, name='team_list'),
    path('admin/groups/', views.group_list, name='group_list'),
    path('admin/approve_players/<uuid:player_id>', views.approve_player, name='approve_player'),
    path('admin/view_team_member_admin/<uuid:team_id>/', views.view_team_members_admin, name='view_team_members_admin'),
    path('admin/approve_team/<uuid:team_id>', views.approve_team, name='approve_team'),
    # path('player/print_receipt/<uuid:payment_id>/', views.print_receipt, name="print_receipt"),
    # path('player/profile/', views.player_profile, name='player_profile'),
]