# Generated by Django 5.2.6 on 2025-09-08 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewallz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_size', models.PositiveIntegerField(default=0, help_text='Maximum players allowed (0 = unlimited).')),
                ('is_locked', models.BooleanField(default=False, help_text='If locked, membership cannot change.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(help_text='College this group belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='player_groups', to='firewallz.college')),
                ('players', models.ManyToManyField(blank=True, help_text='Players in this group (must all belong to the same college)', related_name='approval_groups', to='firewallz.player')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
    ]
