# Generated by Django 5.2.6 on 2025-09-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewallz', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_verified_by_firewallz',
            field=models.BooleanField(default=False),
        ),
    ]
